services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
       - .:/app
  redis:
    image: redis:latest
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_AUTH}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/var/lib/redis/data
  
  queue:
    image: bodsch/docker-beanstalkd:1.10

  beanstalkd-ui:
    image: thedavis/beanstalkd-ui:0.0.2
    links:
      - queue
    ports:
      - 8902:80
    environment:
      - BEANSTALKD_HOST=queue
      - BEANSTALKD_PORT=11300
volumes:
  redis:
    driver: local