services:
  api:
    build:
      context: .
      args:
        TARGET: api
    ports:
      - "8000:8080" 
    env_file:
      - .env
    depends_on:
      - redis
      - queue
    command: ["go", "run", "./cmd/api/main.go"]
    volumes:
        - .:/app
  worker:
    build:
      context: .
      args:
        TARGET: worker
    env_file:
      - .env
    environment:
      BEANSTALK_ADDR: queue:11300
    depends_on:
      - queue
    command: ["go", "run", "./cmd/worker/main.go"]

  redis:
    image: redis:latest
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_AUTH}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/var/lib/redis/data
  
  queue:
    image: bodsch/docker-beanstalkd:1.10

  beanstalkd-ui:
    image: thedavis/beanstalkd-ui:0.0.2
    links:
      - queue
    ports:
      - 8902:80
    environment:
      - BEANSTALKD_HOST=queue
      - BEANSTALKD_PORT=11300
volumes:
  redis:
    driver: local